### PR TITLE
feat: specification in Markdown

### PR DESCRIPTION
**Pull request by nicorikken**
Specification converted to Markdown format. Using MkDocs and its ecosystem of plugins and themes to render it.

Work left to do:

### Content

- [x] Convert remaining part of the document
- [x] Links
- [x] Footnotes
- [x] Add captions to images
- [x] Bibliography links --> converted to footnotes in https://github.com/shapeshifter/shapeshifter-specification/pull/67/commits/ec82772995b6f6e16d17720d7ff4b3854bb94f3e
- [x] Remove numerical references, like "Chapter 2", "Section 2.5.3" and "Figure 2.4"
- [x] Finetune pdf export, ideally also having a combined pdf export option like supplied by https://github.com/zhaoterryy/mkdocs-pdf-export-plugin --> this still needs some work https://github.com/iSOLveIT/mkdocs-pdf-generate/issues/17 
- [x] Convert URLs to links
- [x] Add SPDX headers: `reuse annotate -c "Contributors to the Shapeshifter project" -l "Apache-2.0" -y 2020-2023 -r --skip-unrecognised ./`
- [x] Detailed human check against the original document
- [x] Increase size of pictures to span full width
- Prevent tracking with Google Fonts to comply with GDPR. Perhaps using the plugin in the theme, which requires $15/month sponsorship https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=privacy#built-in-privacy-plugin --> **Deferred**
- Link or embed (using https://facelessuser.github.io/pymdown-extensions/extensions/snippets/) the xsd files. --> **Deferred**

### Automation

- Automated formatting and spelling checks --> **Deferred**
- [x] Configure [Mike](https://github.com/jimporter/mike) for versioning 
- [x] Setup a GitHub Actions for publishing supporting all features
- PR-specific preview with https://github.com/rossjrw/pr-preview-action/ --> **Deferred**
- Detect dead links --> **Deferred**

### CODE REVIEW

**Comment by KoviaX** [comment]
Thanks for your contribution so far! The diagrams don't all seem to render correctly, most obviously on the "Validate phase" page, but I think the original SVG's already show issues here on GitHub. Can you verify they look right on your local machine?

**Comment by nicorikken** [comment]
@KoviaX in the mean time the rendering should be ok, also rendering fine on GitHub. For example https://github.com/shapeshifter/shapeshifter-specification/blob/2c3028b0c08c48b952f6457db1ee956fb6123a40/docs/assets/images/use-case-3-10-exchange-of-flexoffer.svg Can you confirm?

**Comment by Edward-Ross-Gridimp** [comment]
Checked and confirmed that metering changes and service-type change have been included in the new documements.

**Review by Edward-Ross-Gridimp — APPROVED** [review]
Checked and confirmed that metering changes and service-type change have been included in the new documents.

Checked that html and pdf versions are both readable with working nav and content.

**Review by RobbenRiksen — APPROVED** [review]
I did a high level review of the specification and checked in more detail a sample of the diagrams and message descriptions.

**Comment by KoviaX** [comment]
I'm still seeing some local issues related to font, but it seems reasonable to me to address those later, merged!

**Pull request merged**
